use_frameworks!

platform :ios, '9.0'

target 'BottomSheetSlider_Example' do
  pod 'BottomSheetSlider', :path => '../'

  target 'BottomSheetSlider_Tests' do
    inherit! :search_paths

    
  end
end
